version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

orbs:
  terraform: "circleci/terraform@3.2.1"

executors:
  default:
    docker:
      - image: hashicorp/terraform:1.5.5
    resource_class: small
    working_directory: "/tmp/terraform"
    environment:
      TF_INPUT: 0
      TF_IN_AUTOMATION: 1

jobs:
  fmt-terraform:
    executor: default
    steps:
      - checkout
      - terraform/init:
          path: terraform/
      - terraform/fmt:
          path: terraform/
      - terraform/validate:
          path: terraform/

  plan-terraform:
    executor: default
    steps:
      - checkout
      - terraform/init:
          path: terraform/
      - terraform/plan:
          path: terraform/

  apply-terraform:
    executor: default
    steps:
      - checkout
      - run: cd terraform/
      - terraform/init:
          path: terraform/
      - terraform/apply:
          path: terraform/

workflows:
  version: 2

  deploy-to-development:
    jobs:
      - fmt-terraform:
          name: fmt-terraform-dev
          context: trade-tariff-terraform-aws-development
          <<: *filter-not-main

      - plan-terraform:
          name: plan-terraform-dev
          context: trade-tariff-terraform-aws-development
          <<: *filter-not-main
          requires:
            - fmt-terraform-dev

      - apply-terraform:
          name: apply-terraform-dev
          context: trade-tariff-terraform-aws-development
          <<: *filter-not-main
          requires:
            - plan-terraform-dev
  
