version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

orbs:
  terraform: "circleci/terraform@3.2.1"

executors:
  default:
    docker:
      - image: hashicorp/terraform:1.5.5
    resource_class: small
    working_directory: "/tmp/terraform"
    environment:
      TF_INPUT: 0
      TF_IN_AUTOMATION: 1

jobs:
  fmt-terraform:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/fmt:
          path: terraform/
      - terraform/validate:
          path: terraform/

  plan-terraform:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/plan:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend

  apply-terraform:
    executor: default
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - terraform/init:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend
      - terraform/apply:
          path: terraform/
          backend_config_file: backends/<< parameters.environment >>.tfbackend

workflows:
  version: 2

  deploy-to-production:
    jobs:
      - fmt-terraform:
          name: fmt-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          <<: *filter-not-main

      - plan-terraform:
          name: plan-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          <<: *filter-not-main
          requires:
            - fmt-terraform-prod

      - apply-terraform:
          name: apply-terraform-prod
          context: trade-tariff-terraform-aws-production
          environment: production
          <<: *filter-main
          requires:
            - plan-terraform-prod
